<h3 class="text-xl font-bold pb-4">Roses is <span class="text-red-500">Red</span></h3>
<p>
Roses is <span class="text-red-500">red</span>.<br>
Violets is <span class="text-fuchsia-500">blue</span>.<br>
<pre>        All I wanna do is <span class="text-sky-500">code</span></pre>.<br>
<span class="text-yellow-500" id="hoverText">Wow</span>.<br>
</p>
<audio id="mySound" src="/sounds/wow.mp3" preload="auto"></audio>
<script src="/js/play_sounds.js"></script>
